services:
    jenkins:
        build:
            context: ./jenkins
            dockerfile: Dockerfile
        ports:
            - "9080:8080"
            - "50001:50001"
        volumes:
            - "./jenkins/data/var/jenkins_home:/var/jenkins_home"
        restart: always
        container_name: "jenkins_cidm"
    artifactory:
        build:
            context: ./artifactory
            dockerfile: Dockerfile
        ports:
            - "9081:8081"
        volumes:
            - "./artifactory/data/var/opt/jfrog/artifactory:/var/opt/jfrog/artifactory"
        restart: always
        container_name: "artifactory_cidm"
    grafana:
        build:
            context: ./grafana
            dockerfile: Dockerfile
        ports:
            - "9082:3000"
        volumes:
            - "./grafana/data/var/lib/grafana:/var/lib/grafana"
        restart: always
        container_name: "grafana_cidm"
    prometheus:
        build:
            context: ./prometheus
            dockerfile: Dockerfile
        ports:
            - "9090:9090"
        volumes:
            - "./prometheus/data/etc/prometheus:/etc/prometheus"
        restart: always
        container_name: "prometheus_cidm"
